apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-svc"
  namespace: "rs2"
  labels:
    app: "mongo-db"
spec:
  ports:
    - name: "mongodb"
      port: 27022
      targetPort: 27017
      nodePort: 30019
  type: NodePort
  selector:
    app: "mongo-db"
